// Task O.1 — weekly cron wrapper around runFreshnessPass (freshness.ts).
// Mirrors engine.ts's CLI shape: injected fetch/clock at the boundary, a
// testable exported core function, and process.exit confined to the
// import.meta.url guard.
//
// There is NO dry-run mode here — freshness.ts documents that every pass
// writes repo.update; this wrapper does not add one. Its only job is to run
// the pass, emit a run summary of FreshnessOutcome[] counts, and — this is
// the regression that matters — never swallow the partial outcomes that ride
// on a thrown FreshnessPassError. A plain `.catch(console.error)` would print
// the stack and discard the summary of every row that DID process before the
// corrupt one.
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { sourcesRepo as realSourcesRepo } from "../persistence/repos/sources";
import { FreshnessPassError, runFreshnessPass, type FreshnessOutcome, type FreshnessRepo } from "./freshness";
import type { FetchLike } from "./validate";

const DEFAULT_REPORT_PATH = "docs/superpowers/reports/freshness-run-latest.md";

export interface FreshnessCliOptions {
  repo: FreshnessRepo;
  /** Injected fetch — never the global, same discipline as freshness.ts/validate.ts. */
  fetch: FetchLike;
  /** Clock injection, passed straight through to runFreshnessPass. */
  now?: () => number;
  reportPath?: string;
  log?: (message: string) => void;
}

export interface FreshnessCliResult {
  exitCode: number;
  outcomes: FreshnessOutcome[];
}

function summarize(outcomes: FreshnessOutcome[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const o of outcomes) counts[o.action] = (counts[o.action] ?? 0) + 1;
  return counts;
}

function renderSummary(args: {
  outcomes: FreshnessOutcome[];
  failures: ReadonlyArray<{ id: string; message: string }>;
  startedAt: number;
  finishedAt: number;
}): string {
  const { outcomes, failures, startedAt, finishedAt } = args;
  const counts = summarize(outcomes);
  const seconds = ((finishedAt - startedAt) / 1000).toFixed(1);
  const lines: string[] = [
    `# Freshness run — ${failures.length > 0 ? "PARTIAL (malformed rows)" : "OK"}`,
    "",
    "Generated by `npm run sources:freshness`.",
    `Started ${new Date(startedAt).toISOString()}, finished ${new Date(finishedAt).toISOString()} (${seconds}s).`,
    `Rows processed: **${outcomes.length}**`,
    "",
    "| action | count |",
    "|---|---|",
    ...Object.keys(counts)
      .sort()
      .map((k) => `| ${k} | ${counts[k]} |`),
    "",
  ];
  if (failures.length > 0) {
    lines.push(`## Malformed rows (${failures.length})`, "", ...failures.map((f) => `- \`${f.id}\`: ${f.message}`), "");
  }
  return lines.join("\n");
}

/**
 * The testable core: runs one freshness pass, prints + writes a run summary,
 * and returns a process-exit-shaped result instead of calling process.exit —
 * that call is confined to the import.meta.url guard below, mirroring
 * engine.ts.
 *
 * Catches {@link FreshnessPassError} specially: its `outcomes`/`failures` ride
 * on the error object, so they are pulled off it and folded into the same
 * summary a clean pass would produce, rather than being discarded with a bare
 * `console.error(err)`.
 */
export async function runFreshnessCli(opts: FreshnessCliOptions): Promise<FreshnessCliResult> {
  const { repo, fetch: fetchFn, now = Date.now, reportPath = DEFAULT_REPORT_PATH, log = (m: string) => console.log(m) } = opts;
  const startedAt = now();

  let outcomes: FreshnessOutcome[];
  let failures: ReadonlyArray<{ id: string; message: string }> = [];
  let exitCode = 0;

  try {
    outcomes = await runFreshnessPass({ repo, fetch: fetchFn, now });
  } catch (err) {
    if (!(err instanceof FreshnessPassError)) throw err;
    // THE regression: pull the partial outcomes off the error instead of
    // discarding them with the throw.
    outcomes = err.outcomes;
    failures = err.failures;
    exitCode = 1;
    log(`freshness: pass completed with ${failures.length} malformed row(s) — see summary below`);
  }

  const finishedAt = now();
  const summary = renderSummary({ outcomes, failures, startedAt, finishedAt });
  log(summary);
  await mkdir(dirname(reportPath), { recursive: true });
  await writeFile(reportPath, summary, "utf8");
  log(`freshness: report written to ${reportPath}`);

  return { exitCode, outcomes };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

export interface Cli {
  reportPath: string;
}

export function parseArgs(argv: string[]): Cli {
  const cli: Cli = { reportPath: DEFAULT_REPORT_PATH };
  for (const arg of argv) {
    if (arg.startsWith("--report=")) cli.reportPath = arg.slice("--report=".length);
    else throw new Error(`sources:freshness: unknown argument "${arg}" (expected --report=<path>)`);
  }
  return cli;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const cli = parseArgs(process.argv.slice(2));
  runFreshnessCli({ repo: realSourcesRepo, fetch: (url, init) => fetch(url, init), ...cli })
    .then(({ exitCode }) => process.exit(exitCode))
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
